### ISSUE TITLE
função em php

### ISSUE THREAD

**Issue by marcelocecin** [victor-torres/sinesp-client#1]
blz victor ?

vc sabe como chamar essa função return hmac_key.digest().encode('hex') no PHP ?

valeu

**Comment by StefanYohansson** [comment]
O script é em python não em PHP, você não tem como rodar a função `hmac_key.digest()` no PHP, não seria interessante usa-lo para carregar uma biblioteca em python, mas se é o que deseja:
Você pode usar `shell_exec` para rodar um comando externo e assim obter o resultado. :)
Porém você pode acabar caputrando um erro de python ao invés da saída esperada.

http://stackoverflow.com/questions/19735250/running-a-python-script-from-php

**Comment by marcelocecin** [comment]
essa função digest() faz o que exatamente ?

**Comment by StefanYohansson** [comment]
https://docs.python.org/2/library/hmac.html#hmac.HMAC.digest

**Comment by marcelocecin** [comment]
será que esse código funciona ? https://gist.github.com/reusee/1035975

**Comment by StefanYohansson** [comment]
esse código é de 5 anos atrás.

**Comment by victor-torres** [comment]
@marcelocecin a biblioteca foi feita em Python e faz sentido oferecermos suporte apenas para essa linguagem. Você teria alguma dúvida específica a respeito da implementação ou portabilidade do script para o PHP?

@StefanYohansson já explicou como executar códigos Python dentro do PHP. É uma linguagem bem simples e os exemplos estão todos no README do repositório.

Se você precisar de um suporte individual para fazer a biblioteca funcionar com seu código em PHP, por favor entrar em contato via e-mail.

**Comment by StefanYohansson** [comment]
haha :8ball:

**Comment by marcelocecin** [comment]
blz consegui executar pelo PHP obrigado a todos

**Comment by StefanYohansson** [comment]
você poderia compartilhar o que usou para caso alguém mais esteja interessado?

**Comment by marcelocecin** [comment]
usei este artigo que vc postou: http://stackoverflow.com/questions/19735250/running-a-python-script-from-php
