### ISSUE TITLE
Atualização do Sinesp

### ISSUE THREAD

**Issue by cleandersonlobo** [victor-torres/sinesp-client#10]
Olá, Beleza?

O Sinesp foi atualizado retorna o mensagem: "Versão desatualizada. Favor atualizar o Aplicativo".

Já dei um dei uma olhada nas modificações e foi alterado tanto url da consulta como também foi adiciona mais informações no XML. 

Eu ainda não consegui ainda, em todas minha tentativas só retorna a mensagem "Chamada para o serviço é inválida."

Se puder ajudar eu agradeço. Abraço!

**Comment by victor-torres** [comment]
Atualizaram a API (URL + Corpo) e também o segredo utilizado em cada request.

**Comment by anderson82lima** [comment]
Boa noite Victor, como posso resolver este caso, estava testando seu código para um estudo.

Sabe como posso obter estas informações ?

Obrigado.

**Comment by victor-torres** [comment]
@anderson82lima #11
