### ISSUE TITLE
Versão desatualizada. Favor atualizar aplicativo.

### ISSUE THREAD

**Issue by ilbolzan** [victor-torres/sinesp-client#11]
Fui testar a API, mas estou recebendo essa mensagem de erro.
Será que é algo que fiz de errado ou eles mudaram o acesso ao WebService?

``` Python
>>> from sinesp_client import SinespClient
>>> sc = SinespClient()
>>> sc.search('IPI5651')
{'city': None, 'return_message': 'Versão desatualizada. Favor atualizar aplicativo.', 'chassis': None, 'status_message': None, 'model': None, 'brand': None, 'year': None, 'state': None, 'return_code': '1', 'date': None, 'color': None, 'plate': None, 'model_year': None, 'status_code': None}
>>>
```

**Comment by fpg1503** [comment]
Aparentemente agora é necessário fazer uma chamada de captcha (`http://sinespcidadao.sinesp.gov.br/sinesp-cidadao/captchaMobile.png?time=TIME`) que retorna um cookie de sessão que deve ser enviado. Além disso agora também é enviado um UUID como `k`, a data (`yyyy-MM-dd HH:mm:ss`) como `l` e uma constante de versão do serviço (atualmente `1204fdd387279490261aaf95a6567f64` como `m`. Não sei quanto tempo o captcha vale ou se o limite de requests aumentou.

**Comment by fpg1503** [comment]
Além disso a maneira como é gerado o token da placa mudou, vou ver se consigo fazer engenharia reversa nisso no final de semana.

**Comment by fpg1503** [comment]
O novo segredo é `3ktTqS63LBPlOT3WgFlk`

**Comment by lucazFerreira** [comment]
Complementando com os amigos: O formato do novo SOAP é:

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Header>
<b>GT-S1312L</b>
<c>Android</c>
<d>9.0</d>
<e>SinespCidadao</e>
<f>127.0.0.1</f>
<g>***AQUI VAI O HASH GERADO***</g>
<j></j>
<k></k>
<l>2016-10-21 11:52:21</l> //data atual SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
<m>1204fdd387279490261aaf95a6567f64</m> //fixo
</soap:Header>
<soap:Body>
<webs:getStatus xmlns:webs="http://soap.ws.placa.service.sinesp.serpro.gov.br/">
<a>***PLACA DO VEICULO***</a>
</webs:getStatus>
</soap:Body>
</soap:Envelope>

Caso queiram, adicionem meu whatsapp para atualizarmos nossos serviços assim que tivermos novas alterações: (92) 99266-8054

**Comment by lucazFerreira** [comment]
Complementando com os amigos, segue o novo formato do SOAP:
Caso queiram, adicionem no Whatsapp para futuramente podermos debater sobre atualizações do serviço SINESP. (92) 99266-8054

`<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap:Header>
<b>GT-S1312L</b>
<c>Android</c>
<d>9.0</d>
<e>SinespCidadao</e>
<f>127.0.0.1</f>
<g>'. $hash .'</g>'//Fixo
<j></j>' //captcha
<k></k>
<l>2016-10-21 11:52:21</l>' //data atual SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
<m>1204fdd387279490261aaf95a6567f64</m>
</soap:Header>
<soap:Body>
<webs:getStatus xmlns:webs="http://soap.ws.placa.service.sinesp.serpro.gov.br/">
<a>'. $placa .'</a>
</webs:getStatus>
</soap:Body>
</soap:Envelope>;`

**Comment by lucazFerreira** [comment]
Segue também o novo Post: 
Pode ser http, ou https.
> https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa

**Comment by victor-torres** [comment]
Os parâmetros no corpo da requisição realmente mudaram, como também o segredo da aplicação que agora parece ser dinâmico. Dei uma olhada na nova aplicação e é perfeitamente possível repetir o processo, mas não tenho tempo disponível nem sei se quero continuar a ter de atualizar a biblioteca quando na verdade o SINESP deveria fornecer uma API pública para acesso a esses dados. 

Talvez a comunidade devesse se concentrar em conquistar o acesso livre e público fornecido pelo próprio governo. Seria melhor pra todo mundo. Existe uma grande cobrança principalmente via e-mail e pouca ajuda e motivação por parte da comunidade. Não recebo para desenvolver o código que compartilho aqui gratuitamente. Deveríamos pressionar a abertura da API, não cobrar um trabalho voluntário feito com a melhor das intenções de ajudar a comunidade.

Se alguém puder/quiser enviar um Pull Request com as correções necessárias para que a biblioteca volte a funcionar, revisarei e lançarei uma nova versão caso esteja funcionando corretamente.

**Comment by fpg1503** [comment]
@victor-torres entendo seu posicionamento. Acho que tudo que você precisa está aí nos meu comentários acima. Pelo que eu li no assembly da lib superplacas não está dinâmico não, extrai esse segredo aí acima e ele funciona bem. A lib superplacas só tem umas checagens para garantir que ela está sendo rodada no app deles. Estou sem meu computador hoje, amanhã ou segunda abro um PR pra você se ninguém tiver ainda.

**Comment by fpg1503** [comment]
Fiz um PR, num sou dev Python no dia-a-dia, se tiver alguma boa prática que eu não segui por favor avise :)

**Comment by victor-torres** [comment]
Muito obrigado por sua contribuição, @fpg1503. Estava recebendo muitos e-mails, alguns bem educados, outros até agressivos, requisitando a atualização da biblioteca. É bom ver pessoas dispostas a ajudar e a contribuir com o projeto! 

Já fiz merge e lancei a nova versão no PyPI. Ficou muito bom seu código! Também te adicionei à lista de contribuidores.

**Comment by fabianoarruda** [comment]
@fpg1503 vc poderia dar mais detalhes de como fez pra extrair esse segredo da lib? Parece que mudou novamente, teoricamente teria que analisar essa lib e extrair o novo segredo...

**Comment by fpg1503** [comment]
@fabianoarruda claro! Eu baixo o APK mais novo no computador, descompacto ele, decompilo o código Java e vejo como é feita a requisição. Lá dentro na última versão havia uma chamada para uma função que era definida em uma biblioteca nativa, na lib-superplacas. Então eu peguei dentro do APK descompactado o binário da lib-superplacas para a arquitetura ARM (pois entendo melhor código de montagem de ARM), desmontei e li a definição dele, na versão passada ele checava se o app no qual a lib estava rodando era o do SinespCidadao de Android e lá dentro encontrei o segredo novo. Chegando em um computador eu vejo se não está mais funcionando e o segredo novo caso tenha mudado.

**Comment by bgastaldi** [comment]
@victor-torres e @fpg1503, nós temos um grupo onde o @fabianoarruda também faz parte com seletas pessoas (7 membros) que conseguimos converter o app para diversas linguagens depois dele rodando. Caso queiram fazer parte do mesmo, por favor me enviem uma DM via twitter @bgastaldi com seus telefones.

**Comment by thiagotalma** [comment]
A quem possa interessar:
http://www.denatran.gov.br/images/Portarias/2016/Portaria0152016_nova.pdf

**Comment by rickduarte** [comment]
Valeu @thiagotalma !
Só uma pergunta: você sabe onde encontrar essa tabela de valores estabelecidos pelo DENATRAN que eles mencionam no Capítulo 1 - Artigo 2?

**Comment by bgastaldi** [comment]
@thiagotalma @rickduarte Obrigado.
Nós já atualizamos o WS e voltou a funcionar. Breve acredito que o @victor-torres disponibilize aqui pra vocês.

**Comment by lucazFerreira** [comment]
Se voces puderem adicionar meu numero no grupo de voces eu agradeço. Tenho um app que trabalha com consultas de multas, e utilizo tbm o sinesp.
Desde ja, agradeço: (92) 99266-8054

Obter o Outlook para Android<https://aka.ms/ghei36>



On Sun, Nov 20, 2016 at 8:54 PM -0400, "Bruno Gastadi" <notifications@github.com<mailto:notifications@github.com>> wrote:


@thiagotalma<https://github.com/thiagotalma> @rickduarte<https://github.com/rickduarte> Obrigado.
Nós já atualizamos o WS e voltou a funcionar. Breve acredito que o @victor-torres<https://github.com/victor-torres> disponibilize aqui pra vocês.

-

**Comment by thiagotalma** [comment]
> Só uma pergunta: você sabe onde encontrar essa tabela de valores estabelecidos pelo DENATRAN que eles mencionam no Capítulo 1 - Artigo 2?

Infelizmente não sei dizer.
Na verdade eu não sei nada a respeito dessa legislação, Sou só mais um consumidor dessa "API" e quis colaborar na discussão encontrando a legislação que regra a disponibilização dos dados. Pode ser útil caso alguém tenha interesse em montar um webservice "legalizado".

Essa dica vale para qualquer dado do governo: Toda informação não sigilosa deve estar disponível para consulta pública. Sempre que precisarem de acessar alguma informação procure uma portaria ou decreto que diz quais as condições para acessá-la.

**Comment by victor-torres** [comment]
@fpg1503 exatamente o procedimento que uso, acho que não tem muito como ser diferente disso. A única alternativa (cara), seria pré-gerar todos os tokens para todas as placas possíveis e consultar isso num banco de dados local (SQLite ou Protocol Buffer).

@bgastaldi segui no Twitter, só dá pra mandar DM depois que seguir de volta, acredito.

@thiagotalma acho que foi o que comentei no README, a lei de acessso à informação ou transparência deveria garantir uma API pública para acesso a esses dados. E não apenas acesso, mas a possibilidade de mecanizar/robotizar as consultas. Ruim é que deve ser muito difícil brigar por isso, demanda tempo, investimento... 

Agora não entendo a dificuldade deles em organizar uma API direitinho, com rate limit etc. Melhor do que ficar gerando essas soluções miraboantes que só prejudicam o usuário. Quem usa o app agora tem que atualizar toda vez quando eles resolver mudar a chave. Isso deve gerar um custo absurdo com dados e atrapalha o trabalho de um guarda, vigilante, policial ou até cidadão comum...

**Comment by thiagotalma** [comment]
@bgastaldi O seu WS é público? Você pode compartilhar?
Ou me enviar privado?

**Comment by rickduarte** [comment]
Pessoal, a versão que estou do Sinesp Cidadão (4.1) pra Android está com um token diferente.
token = "TRwf1iBwvCoSboSscGne"

**Comment by bgastaldi** [comment]
Sim, mudou o WS também . Já passamos pro Victor, breve ele atualizará

**Comment by rickduarte** [comment]
Valeu @bgastaldi !
Eu já estava achando que tinha feito alguma cagada na conversão pra C#.

**Comment by bgastaldi** [comment]
Outra coisa a versão Android e diferente da do IOS. Tanto o Token quanto o WS.

**Comment by monteirosk** [comment]
Fiz umas modificações body.xml troquei a senha e voltou a funcionar.

**Comment by victor-torres** [comment]
Pode mandar um Pull Request, @monteirosk?

**Comment by victor-torres** [comment]
Obrigado por sua contribuição, @monteirosk. Já fiz merge no Pull Request, te adicinei como contribuidor e lancei a nova versão 1.6 no pypi.

**Comment by thiagotalma** [comment]
@monteirosk vou entrar em contato contigo no email, ok?

**Comment by thiagotalma** [comment]
O serviço continua firme, mas tá dureza é conseguir um proxy confiável para fazer as requisições....

O que vocês estão usando? O que sugerem como solução?

**Comment by monteirosk** [comment]
@thiagotalma ok, pode sim amigo
monteiro.william4@gmail.com

**Comment by matheusleite** [comment]
Outra atualização....

**Comment by bgastaldi** [comment]
Necessário colocar o https!

**Comment by matheusleite** [comment]
@bgastaldi consigo rodar local tranquilo, mas quando coloco no meu servidor na Amazon não funciona. Preciso instalar um certificado SSL na minha máquina? É isso?

**Comment by fabianoarruda** [comment]
@matheusleite Até onde eu sei, só funciona se a requisição se originar de um IP do Brasil. Se o seu servidor fica fora do país, não vai funcionar.

**Comment by lucazFerreira** [comment]
Matheus, o SINESP bloqueia acesso de IPs de fora do Brasil. Se quiser trabalhar com a consulta em seu servidor, terá que utilizar um proxy.


Atenciosamente,


Lucas Ferreira

________________________________
De: Matheus Leite <notifications@github.com>
Enviado: sexta-feira, 2 de junho de 2017 18:07:53
Para: victor-torres/sinesp-client
Cc: lucazFerreira; Comment
Assunto: Re: [victor-torres/sinesp-client] Versão desatualizada. Favor atualizar aplicativo. (#11)


@bgastaldi<https://github.com/bgastaldi> consigo rodar local tranquilo, mas quando coloco no meu servidor na Amazon não funciona. Preciso instalar um certificado SSL na minha máquina? É isso?

**Comment by matheusleite** [comment]
@lucazFerreira Mesmo com o proxy não está funcionando.

Na versão em PHP do código funciona no meu servidor de fora do país com proxy, mas a request é MUITO demorada.

**Comment by lucazFerreira** [comment]
Estranho.. eu trabalho com um servidor hospedado fora do Brasil, utilizando proxys brasileiros e funcionam bem. É claro que o tempo de consulta dependerá do serviço de proxy que você está utilizando, bem como o status de estabilidade do SINESP (que algumas vezes fica lento e instável). Eu iniciei trabalhando com a utilização de proxys publicos, e por mais que eu filtrasse só os melhores, ainda assim, a consulta era sempre lenta. Então, comprei proxys privados para esse trabalho.


Outro ponto que tem que ser observado, é se o IP do proxy ao qual você está enviando a solicitação não está temporariamente bloqueado pelo SINESP. Talvez você já saiba, mas não custa frisar pros demais que venham a ler, o SINESP possui um controle que bloqueia IPs que estejam realizando muitas requisições. Então, se você trabalha com um volume de consultas relativamente alto, em um único Proxy, talvez precise fazer um revezamento.

________________________________
De: Matheus Leite <notifications@github.com>
Enviado: sexta-feira, 2 de junho de 2017 18:59:01
Para: victor-torres/sinesp-client
Cc: lucazFerreira; Mention
Assunto: Re: [victor-torres/sinesp-client] Versão desatualizada. Favor atualizar aplicativo. (#11)


@lucazFerreira<https://github.com/lucazferreira> Mesmo com o proxy não está funcionando.

Na versão em PHP do código funciona no meu servidor de fora do país com proxy, mas a request é MUITO demorada.

**Comment by monteirosk** [comment]
Eu vi que os aplicativos que fazem pesquisa nos sinesp atualizaram, acredito que deve ter trocado o token, não tive tempo de olhar melhor.

**Comment by monteirosk** [comment]
meu chatbot esta funcionando no telegram ele e em php.

**Comment by rafaelgasparini** [comment]
falae galera td joia? cara eu to usando o sinesp-nodejs ele soh me retorna { codigoRetorno: '7',
  mensagemRetorno: 'Versão desatualizada. Favor atualizar aplicativo.' } alguem pode me dar um help?

**Comment by victor-torres** [comment]
@rafaelgasparini por favor, veja a outra issue #30
