### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by monteirosk** [victor-torres/sinesp-client#13]
o app parou de funcionar

{"state": null, "model_year": null, "color": null, "date": null, "chassis": null, "status_message": null, "brand": null, "year": null, "model": null, "return_message": "Vers\u00e3o desatualizada. Favor atualizar aplicativo.", "return_code": "7", "city": null, "plate": null, "status_code": null}

**Comment by victor-torres** [comment]
duplicated #11
