### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by vctrmp** [victor-torres/sinesp-client#15]
Oi Victor, tudo joia?

Por acaso você tem algum esquema para a Sinesp não dar Time-out depois de algumas requisições seguidas? Eu estou trabalhando com uma base de placas razoavelmente grande, mas após alguns requests seguidos, recebo o erro abaixo:
`    print sc.search(license)
  File "/usr/local/lib/python2.7/site-packages/sinesp_client/__init__.py", line 180, in search
    response = self._request(plate).content
  File "/usr/local/lib/python2.7/site-packages/sinesp_client/__init__.py", line 119, in _request
    return requests.post(url, data, headers, proxies=self._proxies, cookies=cookies)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='sinespcidadao.sinesp.gov.br', port=80): Read timed out. (read timeout=None)`

**Comment by thiagotalma** [comment]
Você está usando proxy? Pode ser timeout do proxy, não do server de consulta.
Principalmente se for proxy free.

**Comment by vctrmp** [comment]
Não estou usando proxy, e coloquei um delay de 30 segundos pra cada request:

```
from sinesp_client import SinespClient
import time

sc = SinespClient()

for license in ['XXX1234',...]: 
	time.sleep(60)
	print sc.search(license)
```

Parece que é um bloqueio da Sinesp para bloquear muitos requests. O que eu queria saber é se alguém já descobriu uma forma de contornar este limite, ou qual é o limite exatamente (o limite é por hora? diário? mensal?)

**Comment by thiagotalma** [comment]
Victor, um webservice bem feito sempre tem implementa um `Rating Limit`. Deve ser esse o seu problema.

A solução perfeita para contornar depende do conhecimento das regras de implementação. Acredito que isso você nunca terá.

Precisamos de mais detalhes para poder te ajudar.

- Estamos falando de quantas placas para consultar?
- É uma lista fixa ou todo dia as consultas são novas?
- A consulta é assíncrona ou tem um usuário fazendo a consulta em tempo real?

Então o jeito é ir tentando, testando possibilidades. 
Por exemplo: distribuir as requisições em vários proxys, cada requisição simular um ambiente diferente (user-agent, etc...), e por aí vai....

Você repete a consulta da mesma placa? Caso positivo, faça um db local para evitar que isso aconteça.

No mais, é ir ajeitando com paciência....
Qualquer coisa me chame no privado.

**Comment by victor-torres** [comment]
Apenas um comentário: já vi pessoas querendo utilizar a API do SINESP pra consultar **todas as placas possíveis do Brasil** ou de um estado específico de uma só vez. Gente, por favor, tenham bom senso e não abusem da API.

**Comment by dorathoto** [comment]
aproveitando o mesmo issue, normalmente a SECRET key está sendo trocada a cada quanto tempo? pensei em um uso profissional da ferramenta, para poucas consultas em torno de 300/mês porém vai depender essa estabilidade.

**Comment by vctrmp** [comment]
@thiagotalma @victor-torres ,

Obrigado pelas dicas. Testei bastante durante o final de semana e me parece que o tempo entre consultas de 90 segundos funciona bem (ainda assim recebo alguns time-out, mas com bem menos frequencia).

@thiagotalma, respondendo as tuas perguntas: Evito consultar placas repetidas, e as pesquisas são automaticas (já tenho as placas que preciso pesquisar, apenas configurei um delay entre as consultas).

Vou fechar o issue :)
