### ISSUE TITLE
Isso funciona ou não?

### ISSUE THREAD

**Issue by brenowd** [victor-torres/sinesp-client#16]

**Comment by thiagotalma** [comment]
Para você, espero que não.

**Comment by victor-torres** [comment]
@brenowd, por favor, tente primeiro:

1. clonar o repositório
2. executar o exemplo em python
3. surgindo dúvidas ou problemas, abrir um ticket com a maior quantidade de detalhes possível ou mandar uma mensagem pro pessoal

Estou fechando o ticket por falta de detalhes e por não estar necessariamente associado ao código em si.
