### ISSUE TITLE
Um possível Freela

### ISSUE THREAD

**Issue by alansystem** [victor-torres/sinesp-client#18]
Boa tarde, vi que você sem tem uma aplicação em Phyton que faz consulta no Sinesp para retorno de dados do veículo através da placa, sou programador PHP e de Phyton não entendo nada, gostaria de saber se existe alguma forma de efetuarmos uma integração, lembrando que como tenho um cliente com interesse, estou disposto a pagá-lo pelo serviço, mas primeiro gostaria de saber a possibilidade e como poderíamos fazer.

Obrigado.

**Comment by victor-torres** [comment]
Boa noite.

Existe uma versão gratuita em PHP feita pelo [chapeupreto](https://github.com/chapeupreto/) disponível em [aqui](https://github.com/chapeupreto/sinesp).

Para propostas de trabalho, por favor, entrar em contato comigo através do e-mail pessoal disponível no meu perfil do GitHub: vpaivatorres@gmail.com.
