### ISSUE TITLE
Captcha inválido.

### ISSUE THREAD

**Issue by giovanigenerali** [victor-torres/sinesp-client#2]
Victor, tudo bem?

Consegue me ajudar, está retornando captch inválido:

`
'<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:getStatusResponse xmlns:ns2="http://soap.ws.placa.service.sinesp.serpro.gov.br/"><return><codigoRetorno>5</codigoRetorno><mensagemRetorno>Captcha inv\xe1lido.</mensagemRetorno></return></ns2:getStatusResponse></soap:Body></soap:Envelope>'
`

Fiz essa chamada:

from sinesp_client import SinespClient
sc = SinespClient()
sc._request('AFT0017').content

Obrigado.

**Comment by victor-torres** [comment]
@giovanigenerali você pode substituir a última linha por `sc.search('AFT0017')`?

**Comment by giovanigenerali** [comment]
@victor-torres Sim, eu usei esse método mas estava retornando tudo "none" no parse. Fui ver se achamada estava com algum retorno estranho e vi que estava retornando esse código 5 e a mensagem de retorno captch inválido.
Agora fiz um novo teste e parece que voltou a funcionar.
Vou fechar esse issue e qlq coisa reabro.
Obrigado.
