### ISSUE TITLE
Erro na requisiçaõ

### ISSUE THREAD

**Issue by vieiraeliezer** [victor-torres/sinesp-client#22]
Ao fazer uma consulta de placa recebi a seguinte mensagem de erro:

InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html

Sabe como posso resolver?

**Comment by victor-torres** [comment]
Não é um Error, é um Warning. Se isso não estiver impedindo a consulta de ser feita, não precisa fazer nada.

**Comment by victor-torres** [comment]
O certificado SSL deles não pode ser validado.
