### ISSUE TITLE
Link Captcha

### ISSUE THREAD

**Issue by guialexandree** [victor-torres/sinesp-client#23]
Boa tarde, estou fazendo a transição do código para C#, estou com problemas para pegar o cookie do captcha parece que o link não é um link válido.

Seu código
 `def _captcha_cookie(self):
        """Performs a captcha request and return the cookie."""
        cookies = requests.get('https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/captchaMobile.png', proxies=self._proxies, verify=False).cookies
        jsessionid = cookies.get('JSESSIONID')
        return {'JSESSIONID': jsessionid}`

Meu código 
`HttpWebRequest requestCaptcha = (HttpWebRequest)HttpWebRequest.Create("https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/captchaMobile.png");
requestCaptcha.CookieContainer = new CookieContainer();
requestCaptcha.Method = "GET";
HttpWebResponse resposta = (HttpWebResponse)requestCaptcha.GetResponse();
var cookie = resposta.Cookies["JSESSIONID"];`

Ele retorna com erro = "O servidor remoto retornou um erro: (404) Não Localizado.".
Se eu envio o request sem o cookie eu recebo um envolope = 
`<soap:Body xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><ns2:getStatusResponse xmlns:ns2=\"http://soap.ws.placa.service.sinesp.serpro.gov.br/\"><return><codigoRetorno>1</codigoRetorno><mensagemRetorno>Erro no processamento da consulta.</mensagemRetorno></return></ns2:getStatusResponse></soap:Body>`

**Comment by rickduarte** [comment]
@guialexandree o projeto é PCL ou Windows puro?
Se for PCL, ele não suporta o TLS1.2
Se for Windows, use a classe `Windows.Web.Http.HttpClient`

**Comment by guialexandree** [comment]
Windows

Eu consegui corrigir esse erro era o formato da nada no envio do xml eu estava enviando d/m/a h:m:s enquanto o sistema espera a-m-d h:m:s, porem agora estando dando outra mensagem de retorno

`"<soap:Body xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"><ns2:getStatusResponse xmlns:ns2=\"http://soap.ws.placa.service.sinesp.serpro.gov.br/\"><return><codigoRetorno>6</codigoRetorno><mensagemRetorno>Chamada para o servico e invalida.</mensagemRetorno></return></ns2:getStatusResponse></soap:Body>"`

Esse é meu Xml : 
`strXML.Append("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\" ?>");
                strXML.Append("<v:Envelope xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:d=\"http://www.w3.org/2001/XMLSchema\" xmlns:c=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:v=\"http://schemas.xmlsoap.org/soap/envelope/\" >");
                strXML.Append("<v:Header>");
                strXML.Append("<b>motorola XT1635-02</b>");
                strXML.Append("<c>ANDROID</c>");
                strXML.Append("<d>7.0</d>");
                strXML.Append("<e>4.1.5</e>");
                strXML.Append($"<f>{gera.Next(1, 255)}.{gera.Next(0, 255)}.{gera.Next(0,255)}.{gera.Next(0, 255)}</f>");
                strXML.Append("<g>" + hmac2.ToLower() + "</g>");
                strXML.Append("<h>0.0</h>");
                strXML.Append("<i>0.0</i>");
                strXML.Append("<k/>");
                strXML.Append($"<l>{String.Format("{0:yyyy-MM-dd H:mm:ss}", DateTime.Now)}</l>");
                strXML.Append("<m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m>");
                strXML.Append("</v:Header>");
                strXML.Append("<v:Body>");
                strXML.Append("<n0:getStatus xmlns:n0=\"http://soap.ws.placa.service.sinesp.serpro.gov.br/\">");
                strXML.Append("<a>" + placa + "</a>");
                strXML.Append("</n0:getStatus>");
                strXML.Append("</v:Body>");
                strXML.Append("</v:Envelope>");

                byte[] buffer2 = Encoding.UTF8.GetBytes(strXML.ToString());`

estou usando HttpWebRequest : 

` HttpWebRequest request = (HttpWebRequest)WebRequest.Create("https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2");
                request.CookieContainer = new CookieContainer();
                request.UserAgent = @"ksoap2-android/2.6.0+";
                request.Headers.Add("SOAPAction", "");
                request.ContentType = @"text/xml;charset=UTF-8";
                request.Headers.Add("Accept-Encoding", "gzip");
                request.ContentLength = buffer2.Length;
                request.Method = "POST";
                request.KeepAlive = true;
                request.Accept = @"text/plain, */*; q=0.01";
                request.Headers.Add("Cache-Control", "no-cache");


                using (Stream PostData = request.GetRequestStream())
                {
                    PostData.Write(buffer2, 0, buffer2.Length);`

**Comment by victor-torres** [comment]
@guialexandree, pode entrar em contato comigo via e-mail, por favor? Tem o endereço no meu perfil.
