### ISSUE TITLE
ERRO AO CONSULTAR

### ISSUE THREAD

**Issue by MayronRaifur** [victor-torres/sinesp-client#26]
olá estou com erro ao tentar consultar direto no terminal 

Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sinesp_client import SinespClient
>>> sc = SinespClient()
>>> result = sc.search('AAA1234')
C:\Python27\lib\site-packages\requests-2.8.1-py2.7.egg\requests\packages\urllib3\connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests-2.8.1-py2.7.egg\requests\packages\urllib3\connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by victor-torres** [comment]
Não é um erro, é um alerta porque o certificado do SINESP não é  "válido".
