### ISSUE TITLE
Erro de importação

### ISSUE THREAD

**Issue by josilano** [victor-torres/sinesp-client#27]
Estou usando o projeto com PHP, rodando pelo terminal funciona normal, mas quando o acesso é pelo browser da o seguinte erro:
Traceback (most recent call last): File "/var/www/sinespy/placa.py", line 11, in sc = SinespClient(proxy_address='127.0.0.1', proxy_port=8080) NameError: name 'SinespClient' is not defined

Obs1: estou usando um endereço válido do proxy;
Obs2: sou leigo em python
Como resolvo isso? Obrigado!

**Comment by victor-torres** [comment]
Provavelmente a biblioteca nao esta instalada no mesmo ambiente que o seu servidor web. Estou fechando a issue visto nao se tratar de um problema com a biblioteca em si, mas podemos continuar conversando nesta thread.

O servidor esta rodando na sua maquina ou voce contratou um servico VPS ou de Hospedage Compartilhada?

**Comment by josilano** [comment]
É um VPS da digital ocean LEMP 16.04

**Comment by victor-torres** [comment]
A biblioteca do SINESP está instalada lá?

**Comment by josilano** [comment]
Sim, está. O que acho estranho é funcionar corretamente quando executando pelo terminal, mas quando o acesso é via HTTP ocorre esse erro.

**Comment by victor-torres** [comment]
Loga com o usuário do php-fpm e tenta debugar por lá.

**Comment by josilano** [comment]
Resolvido! O sinesp-client estava instalado no `myuser/.local/`. Obrigado. Agora é só ignorar a msg da issue/26.

**Comment by victor-torres** [comment]
Que bom que deu certo!
