### ISSUE TITLE
Como executar o script Python em PHP com Apache Server no Linux?

### ISSUE THREAD

**Issue by gambiarraweb1** [victor-torres/sinesp-client#28]
Ola, eu possuo um server, ja fiz upload para o server, e o mesmo funciona se executado no putty, pois meu server e debian server, quando digito, ''python placa.py AAA9999'', ele retorna tudo certinho...
mas queria fazer isso ele puxar de um arquivo php
neste server possuo apache, e fiz upload do arquivo de php que fiz e o placa.py para mesma pasta
quando mando executar conforme manual, ele nao retorna nada, fica em branco a pagina

poderia me auxiliar ?

**Comment by victor-torres** [comment]
Seguiu esta página? https://github.com/victor-torres/sinesp-client/wiki/Como-executar-o-c%C3%B3digo-Python-no-PHP

**Comment by victor-torres** [comment]
Por falta de atividade, estou encerrando esta issue. Ela poderá ser reaberta a qualquer momento.
