### ISSUE TITLE
Mensagem: Versão desatualizada.

### ISSUE THREAD

**Issue by kverrna** [victor-torres/sinesp-client#30]
Estou tendo como retorno 
{
    "city": null,
    "model_year": null,
    "plate": null,
    "color": null,
    "status_code": null,
    "brand": null,
    "return_code": "7",
    "date": null,
    "state": null,
    "chassis": null,
    "year": null,
    "return_message": "Versão desatualizada. Favor atualizar aplicativo.",
    "model": null,
    "status_message": null
}

**Comment by lindsey-tonn** [comment]
Estou com o mesmo problema!

**Comment by raulhcordeiro** [comment]
Também estou com o mesmo problema e estou disposto a ajudar a corrigir. O aplicativo está ok e a última atualização foi em Nov/17. Se alguém com mais experiência puder passar uma orientação, agradeço. Vou começar a trabalhar nisso amanhã a tarde. Até lá!

**Comment by vjoao** [comment]
Mesmo problema. Também posso ajudar a corrigir.

**Comment by lindsey-tonn** [comment]
Bom dia galera! Tambe estou disposto a ajudar na correção! Como podemos fazer?

**Comment by vjoao** [comment]
Estou capturando os pacotes do SINESP, acho que basta atualizar a versão do app no POST

**Comment by lindsey-tonn** [comment]
@vjoao podemos trocar uma ideia no slack?

**Comment by oliveirafabio** [comment]
Bom dia pessoal! Estou utilizando a versão em node, porém o problema é o mesmo, gostaria de contribuir para uma solução ou, pelo menos acompanha-los, existe algum canal oficial que vocês utilizam para se comunicar?

**Comment by rickduarte** [comment]
@vjoao eles mudaram novamente a chave, além do POST.

**Comment by lindsey-tonn** [comment]
@oliveirafabio pensei no slack mas até o momento somente por aqui.

**Comment by thiagotalma** [comment]
@victor-torres talvez valha a pena criar um chat no https://gitter.im
É muito prático para centralizar os bate papos do projeto

**Comment by vjoao** [comment]
Mudaram sim. Estou tentando achar a chave nova.

**Comment by rodrigoblz1** [comment]
Mesmo problema aqui... alterar apenas a versão do app no XML não resolveu (uso a versão em Node), aguardando qualquer novidade, obrigado a quem está se empenhando ;D

**Comment by kverrna** [comment]
Eu gostaria de pelo menos saber como ajudar, como vocês fazem engenharia reversa? quais ferramentas de apoio vocês usam para esse fim ?

**Comment by vjoao** [comment]
Aparentemente a nova chave é esta: PiRtabjHDFasdLmioKKt. Estou testando se mudaram algo no algoritmo deles para gerar o token

**Comment by EmersonHenriique** [comment]
@vjoao ensina como pegar a nova chave e como atualizar

**Comment by EmersonHenriique** [comment]
Usando um Debuguer de 1 app que esta funcionando, retornou isso.

`<v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/" xmlns:v="http://schemas.xmlsoap.org/soap/envelope/"><v:Header><b>samsung SM-A300M</b><c>ANDROID</c><d>5.0.2</d><e>4.3</e><f>192.168.15.6</f><g>9b0ffa8d208cdc062a0713ecd5a325b77ddd132e</g><h>0.0</h><i>0.0</i><k></k><l>2018-01-18 12:34:53</l><m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m></v:Header><v:Body><n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/"><a>DLK8650</a></n0:getStatus></v:Body></v:Envelope>`

O XML esta o mesmo, unica diferença é o token :/ que é criptografado em sha1.

**Comment by rickduarte** [comment]
@vjoao Esse código é bem antigo. Hoje em dia eles não usam mais ele. Da última vez, quem conseguiu encontrar o código foi o @luciocorrea .
@luciocorrea , pode ajudar a gente novamente? Ou pelo menos passar onde encontrar a chave. Eu lembro que usou o IDA, certo?

**Comment by EmersonHenriique** [comment]
Link Discord para uma melhor comunicação entre os desenvolvedores!!

https://discord.gg/87mRCJ

**Comment by pedrosalpr** [comment]
Também estou tendo o mesmo problema, está trazendo o código de erro `7` (Versão desatualizada).  Só que estou usando em versão em PHP (feito pelo chapeupreto). Posso contribuir na versão em PHP.

**Comment by vjoao** [comment]
A chave está na biblioteca liblib-superplacas.so.
Usando o `strings` encontrei 2 stings interessantes: `PiRtabjHDFasdLmioKKt` e `PiRtabjHDFgerLmioKKt`
Infelizmente as duas não funcionam como chave.

**Comment by vjoao** [comment]
Vou tentar usar o IDA para pegar a chave

**Comment by igtoth** [comment]
Tem como automatizar o processo de mudança da token/chave ao receber cod:7 ? ou poderia disponibilizar como fazer isso ?

**Comment by alexpozzani** [comment]
@EmersonHenriique qual é o app que está funcionando?

**Comment by lucasjeronimo** [comment]
@alexpozzani é o master placa
https://goo.gl/k1qnM6

**Comment by vjoao** [comment]
Gente, fazer um app funcionar é fácil, já que basta usar a lib. Difícil é descobrir agora o que mudou na forma de gerar o hash... se foi apenas a chave ou o algoritmo em si.

**Comment by raulhcordeiro** [comment]
Boa tarde, pessoal. Como falei no meu último comentário, vou começar a tentar fuçar agora. Encontrei um guia e estou tentando segui-lo: http://www.luiztools.com.br/post/como-fazer-engenharia-reversa-em-apps-android/?gclid=CjwKCAiAqIHTBRAVEiwA6TgJw2eZMnjJ3M5h8LzCC3NJktvOsUfCGPMyj0XFl2Q2JS_crWTsNTi2iRoCUEYQAvD_BwE. Primeiro, gostaria de saber a opinião dos mais experientes se esse é um bom caminho. Segundo, gostaria de saber: alguém já tentou mudar a data/hora do seu sistema pra uma no passado quando a biblioteca estava funcionando?

**Comment by rickduarte** [comment]
@raulhcordeiro Primeiro sobre a data/hora. Não é assim que a chamada funciona. Você passa no XML a versão atual do sistema. Eles bloqueiam qualquer versão diferente. Pra cada versão existe uma chave/token específica. Qualquer coisa diferente não vai funcionar.
Sobre a engenharia reversa, você pode usar os sites:
Pra fazer o download do APK: https://androidappsapk.co/apkdownloader/
Pra descompilar o APK: http://www.javadecompilers.com/apk/
O problema é que a chave esta dentro de um arquivo .so, então é preciso usar um outro programa pra descompilá-lo.

**Comment by igtoth** [comment]
Ja descompilei o .so porem não acho o chave

**Comment by raulhcordeiro** [comment]
E a chave é realmente estática? Ela não muda com a data/hora como o token dos bancos?

**Comment by raulhcordeiro** [comment]
Pergunto isso porque acho estranho não ter havido nenhuma atualização do app original SINESP e ele continuar funcionando normalmente, após a mudança no servidor que exige uma "nova versão". Faz sentido esse raciocínio?

**Comment by rickduarte** [comment]
@raulhcordeiro O Sinesp atualizou em novembro ou dezembro.

**Comment by vjoao** [comment]
É comum os aplicativos continuarem funcionando por um certo período após a atualização, para que a transição seja suave.

**Comment by raulhcordeiro** [comment]
Ok, entendi. Mas minha dúvida é a seguinte: se o app atualizou em Nov/17 e não deixou de funcionar em Jan/18 após uma mudança no controle de acesso do servidor, como ele se adequou? Não parece que a data influência?

**Comment by vjoao** [comment]
Não. Em novembro o endereço do POST mudou, mas o antigo ainda estava funcionando. Agora o antigo provavelmente só dá a mensagem de erro.

**Comment by raulhcordeiro** [comment]
Desculpa a insistência @vjoao , mas minha dúvida persiste. O app SINESP instalado no meu celular continua funcionando e a última atualização dele foi em Nov/17. Isso quer dizer que ele se adequou "sozinho" à mudança implementada no controle de acesso ao serviço em Jan/18, como se já tivesse embarcado no código do app atualizado em Nov/17 que a partir de determinada data ele usaria um novo método para ter acesso ao serviço. Este raciocínio está incorreto?

**Comment by renankof** [comment]
@raulhcordeiro seu raciocínio está errado, pois não faz sentido.

**Comment by rickduarte** [comment]
@raulhcordeiro Pense o seguinte: em nov/2017 eles atualizaram o app, mas mantiveram duas versões funcionando. Assim daria tempo suficiente para o maior número de pessoas possível atualizassem ele e assim evitaria tantos erros. Agora, dois meses depois, eles resolveram retirar a antiga versão do ar.

**Comment by raulhcordeiro** [comment]
Entendi @rickduarte . O que acham de fazer um diff do resultado do decompilador dos 2 apks (o antigo e o novo)?

**Comment by rickduarte** [comment]
Foi criada alguma sala pra discussão sobre o assunto no gitter.im?

**Comment by igtoth** [comment]
Já acharam a solução, mas ninguem compartilha

**Comment by alexpozzani** [comment]
O que estão fazendo só funciona nos apps android, que é criar um FragmentConsulta com o mesmo package do Sinesp e chamando a função nativa 'b' passando a placa, que já traz o token pronto.

**Comment by rickduarte** [comment]
@alexpozzani será que só funciona no android? Será que a gente poderia conversar no Gitter?

**Comment by gpedro** [comment]
@rickduarte estamos todos no Discord: https://discord.gg/fwntSWc

**Comment by alexpozzani** [comment]
esse esquema que eu citei é só android mesmo

**Comment by igtoth** [comment]
@alexpozzani não.. o @vjoao disse que achou a solução, mas não disponibiliza ..

**Comment by luciocorrea** [comment]
Se alguém usa a API comercialmente (não especificamente esse projeto do @victor-torres) e quiser consultoria pra fazer funcionar, é só me procurar ou procurar o @vjoao.

**Comment by jakmelo** [comment]
Pessoal, estou tentando tentando entrar no grupo mas está retornando que o convite expirou. Podem me ajudar? @gpedro @EmersonHenriique ?

**Comment by EmersonHenriique** [comment]
https://discord.gg/h4bHky

**Comment by RobertoBrandini** [comment]
Estou tentando entrar no grupo e o convite expirou. :/

**Comment by gpedro** [comment]
@RobertoBrandini https://discord.gg/EmxyXYf

**Comment by RobertoBrandini** [comment]
@gpedro me mande o convite de novo ja expirou

**Comment by thiagotalma** [comment]
Desta vez o pessoal deve ter feito alguma macumba brava!
Da outra vez rapidinho voltou a funcionar.....

**Comment by lucazFerreira** [comment]
Thiago, na realidade não teve nenhuma macumba braba. Teve sim as pessoas que conseguiram resolver o problema, mas que desta vez não estão buscando a colaboração, e sim o lucro. (o que não deixa de ser errado, aliais são profissionais)

Mas esse é o único fator responsável por esta api ainda não estar corrigida.

________________________________
De: Thiago Talma <notifications@github.com>
Enviado: quinta-feira, 25 de janeiro de 2018 19:28:53
Para: victor-torres/sinesp-client
Cc: Subscribed
Assunto: Re: [victor-torres/sinesp-client] Mensagem: Versão desatualizada. (#30)


Desta vez o pessoal deve ter feito alguma macumba brava!
Da outra vez rapidinho voltou a funcionar.....

**Comment by DinoDoDelphi** [comment]
OK. estou disposto a pagar, qual o contato?

**Comment by lucazFerreira** [comment]
Tem o Lúcio Correa, que foi o que da última vez identificou e corrigiu o contribuiu com o código, e o mesmo também passou o contato do @vjoao<https://github.com/vjoao>.


Eu tentei contato com os 2 mas não tive retorno. Se você conseguir me avise que podemos rachar valor. Meu contato: (92) 99266-8054


________________________________
De: DinoDoDelphi <notifications@github.com>
Enviado: quinta-feira, 25 de janeiro de 2018 20:03:30
Para: victor-torres/sinesp-client
Cc: lucazFerreira; Comment
Assunto: Re: [victor-torres/sinesp-client] Mensagem: Versão desatualizada. (#30)


OK. estou disposto a pagar, qual o contato?

**Comment by vjoao** [comment]
@lucazFerreira @DinoDoDelphi meu telegram é @vmjoao, caso queiram entrar em contato.

**Comment by victor-torres** [comment]
Sobre ter gente cobrando pela solução:

Descobrir o que mudou nessas atualizações da API do SINESP não é um trabalho simples. Muitas vezes eu e outros desenvolvedores compartilhamos a solução gratuitamente aqui no GitHub, em blogs, grupos de chat etc. Raramente alguém reconhece o trabalho. Aqui nesse repositório mesmo tem um botão para doação que poucas pessoas clicam e quando clicam contribuem com um valor bem pequeno. Dá pra comprar um café ou pagar uma cerveja, toda doação é bem-vinda, mas desenvolvimento custa caro e ninguém trabalha de graça. O tempo que a gente para pra se dedicar a resolver os problemas dessa API, a gente tá sem trabalhar, sem ter um lazer, um tempo com a família... 

Agora basta esperar a API quebrar, que logo aparece um monte de gente cobrando uma solução rápida. E o mais interessante é que a maioria dessas pessoas *ganha dinheiro* usando essa API com seus sistemas, consultoria etc. E o que elas fazem pra contribuir com os desenvolvedores que literalmente possibilitam seu negócio? Geralmente nada.

Por vezes eu já ajudei servidores públicos que precisavam agilizar o trabalho em suas repartições (professores universitários com suas pesquisas, até policiais precisavam desse sistama, que o gorverno insiste em deixar fechado). E não cobrei nada por isso. 

Mas infelizmente eu (e outras pessoas também) não tenho tempo pra investir na resolução desses problemas, pricipalmente quando isso não me traz retorno algum. E isso não é de agora. Mas o que já aconteceu foi de pessoas patrocinarem o trabalho de descobrir as mudanças na API porque seu negócio precisava dessa solução. Ou elas precisavam em outra linguagem, que funcionasse em seu sistema atual. Essas pessoas pagaram pelo meu serviço, mas a informação era pública. 


E é isso que o pessoal está fazendo agora. Eles investiram tempo e recursos para descobrir as mudanças e estão cobrando por isso. E enquanto isso ainda se fala em *dividir* o custo da solução pra duas pessoas comprarem juntos e depois compartilharem o código? Gente, vocês são todos desenvolvedores! O que vocês diriam se dois clientes seus dividissem o custo pra usar o seu software e você ao invés de receber o justo, duas vezes, recebesse apenas o valor referente a um deles?

Eu sei que nem todo mundo tem conhecimento técnico pra corrigir esses problemas, mas vamos fazer uma reflexão e evitar sermos oportunistas. Vamos dar de volta, vamos contribuir com a comunidade de software. 

PS: eu não possuo a solução no momento e não planejo investir tempo na descoberta. No entanto, se eu soubesse, provavelmente publicaria aqui no GitHub, se não estivesse sendo patrocinado e o patrocinador não exigisse o sigilo. 

PS2: eu não concordo em cobrar por uma informação que é gratuita e deveria ser livre a todos os brasileiros, mas não é isso que está acontecendo com quem está cobrando! Eles estão cobrando pelo desenvolvimento, pelo tempo investido em descobrir a solução. A informação continua grátis. Seria diferente se alguém vendesse uma outra API que usasse a do SINESP por baixo dos panos, por exemplo. Esse último caso só é justificado se a consulta por placas é um mero detalhe do seu sistema e ele na verdade trás muito mais valor agregado (reconhecimento de placas por imagem, gerenciamento de veículos em estacioamento etc), pois não está vendendo-se o acesso à informação em si.

**Comment by luciocorrea** [comment]
@victor-torres Segue um pequeno relato do que aconteceu de 7 meses pra cá: 

Ano passado quando descobri e divulguei a chave nova, me colocaram num grupo do Telegram. Os membros do tal grupo disseram que se reuniam lá pra "resolver os problemas da API do SERPRO e entregar isso pra comunidade, sem ganho nenhum, **só  pela comunidade mesmo**. 

Pois bem, alguém  resolveu criar também um grupo no Discord, com a mesma justificativa de "trabalharmos juntos na busca de uma solução, também pra comunidade". Tudo corria bem até que alguém nesse grupo sugeriu que eu fizesse uma "vaquinha" pra financiar o desenvolvimento da atualização pra nova versão, já que eu também havia descoberto na última vez. 

Foi só eu falar que havia percebido que a grande maioria usava isso comercialmente e que aceitaria a tal "vaquinha" ou cobraria de quem usa comercialmente e pronto, virei o "demônio mercenário traidor da comunidade".  Disseram que eu estava me gabando de ter conseguido, me chamaram de "moleque mercenário"  e me expulsaram do grupo do Telegram e do Discord. 

Detalhe:  um dos que me xingaram tem um app copycat pra consulta de placas, **com anúncios** e com instalações entre 1 e 5 **milhões** de usuários. 

Depois disso choveram conversas no Telegram, com gente dizendo que usava o código, mas que não ganhava nada com isso. Só usavam "como funcionalidade a mais nos seus sistemas, mas não cobraram nada por isso". E que o "justo" seria eu divulgar pra todo mundo usar. 

Eis que o @vjoao também descobriu as modificações e decidimos que não iríamos divulgar e sim, vender a solução. E assim tem sido desde domingo, dia 21/01. Quem realmente precisava disso funcionando pagou e está satisfeito.

TLDR;  a maioria quer que alguém trabalhe de **graça** pra que eles continuem ganhando dinheiro. Simples assim.

**Comment by monteirosk** [comment]
@victor-torres, @luciocorrea estão apoiados. acho justo receber pelo trabalho.

**Comment by raulhcordeiro** [comment]
Apoiados também. Tentei consertar e vi o quanto é complicado. Por isso reconheço ainda mais o conhecimento necessário para fazer tal trabalho.
Contudo, apoio também quem está buscando o menor custo (que não é o meu caso), pois o argumento (financeiro) é o mesmo: ambas as partes buscam obter o melhor resultado com os recursos de que dispõem. A negociação, assim como as demais práticas do mercado, não devem ser mal vistas (apesar de haver um caráter cultural/religioso pra isso acontecer tão acentuadamente aqui no Brasil) por nós, que afinal, só estamos aqui discutindo sobre esse projeto concebido pelo @victor-torres, porque ele atendia a necessidade de muita gente por um baixo custo (zero). Agora cabe a quem interessar, da MELHOR forma possível que encontrar, contornar o problema que surgiu. Não é essa nossa sina?

**Comment by luciocorrea** [comment]
@raulhcordeiro Excelente colocação. Eu deixei bem claro desde o começo: se você ou a empresa que você trabalha tem tempo disponível e conhecimento necessário pra desenvolver uma solução, façam isso, pra não depender de terceiros. Só que lógico, isso leva tempo. E tempo não é de graça, mesmo que você esteja fazendo em casa, só por diversão.

**Comment by gpedro** [comment]
enquanto ninguém disponibiliza a solução, existe um fallback:
https://www.checkmeucarro.com.br/minha-conta/pesquisaGratis/pesquisar/?placa=IWY9888

**Comment by NewZeek** [comment]
O problema de pagar uma vez é ter que pagar de novo daqui uns meses quando o sinesp atualizar e acabar ficando na mão. Dou os parabéns ao @victor-torres pelo desenvolvimento inicial e manutenção ao longo do tempo, sabemos que é um trabalho complicado para se obter uma informação é pública.

Estou estudando alguns apps e verifiquei que estão utilizando a biblioteca compartilhada do sinesp "liblib-superplacas.so" que contem funções necessárias para gerar a chave, encontrei uma chave "qweqwe484dq7w78s" em um app que utiliza em mesmo algoritmo de criptografia anterior, porém o hash gerada é diferente da que é enviada, podendo ter alguma outra função para chegar à hash final.
A url de consulta continua a mesma "https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2".

O XML funcionando está assim:

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<v:Envelope xmlns:v="http://schemas.xmlsoap.org/soap/envelope/">
<v:Header>
<b>SM-G930</b>
<c>ANDROID</c>
<d>7.0</d>
<e>4.3</e>
<f>192.168.0.17</f>
<g>c2f65a8df55dcd51f1d6715399f1adbc8bc72cd2</g>
<h>0.0</h>
<i>0.0</i>
<k></k>
<l>2018-01-28 14:24:31</l>
<m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m>
</v:Header>
<v:Body>
<n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/">
<a>NZK2018</a>
</n0:getStatus>
</v:Body>
</v:Envelope>

Se tiver algum sucesso informo ao grupo, caso contrário já fica algumas informações para quem tambem está trabalhando para conseguir atualizar. 

Forte abraço.

**Comment by luciocorrea** [comment]
@NewZeek Se o app do Sinesp continuar funcionar, damos a garantia que a nossa solução também funcionará. E quem pagou pela solução não precisará pagar novamente, pelo período contratado.

**Comment by evertonesm** [comment]
Galera alguem conseguiu? Tem algum grupo pra tentar achar a solução? Gostaria de participar

**Comment by evertonesm** [comment]
Alguem diposto a rachar a solução do @vjoao ?

**Comment by ricardotominaga** [comment]
Testem com a chave **Mw6HqdLgQsX41xAGZgsF** e a nova URL. Abracetas.

**Comment by lucianapvs** [comment]
Mudei a chave e a URL também mas está me retornando que o limite de consultas foi excedido sendo que já tem tempo que não faço uma consulta. Alguém pode ajudar?

**Comment by fabioravila** [comment]
@ricardotominaga , pode dar detalhes de como foi feito?

**Comment by ricardotominaga** [comment]
Prestem atenção ao xml. O campo <k> fica vazio.

**Comment by NewZeek** [comment]
Funcionando perfeitamente com chave informada pelo @ricardotominaga e xml que postei, parabens Ricardo.

**Comment by lucianapvs** [comment]
Agora tá tudo funcionando certo, só estava modificar o XML. Valeu @ricardotominaga!

**Comment by lucazFerreira** [comment]
Show pessoal, agradeço de coração! Especialmente ao ricardotominaga, Senhor T e os demais que cooperaram no chat do discorde.

Pros que estão tendo um pouco de dificuldade, resumindo as mudanças:
Nova URL de POST: https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v2

Nova chave: Mw6HqdLgQsX41xAGZgsF

________________________________
De: lucianapvs <notifications@github.com>
Enviado: quarta-feira, 31 de janeiro de 2018 17:52:46
Para: victor-torres/sinesp-client
Cc: lucazFerreira; Mention
Assunto: Re: [victor-torres/sinesp-client] Mensagem: Versão desatualizada. (#30)


Agora tá tudo funcionando certo, só estava modificar o XML. Valeu @ricardotominaga<https://github.com/ricardotominaga>!

**Comment by fabioravila** [comment]
Não querendo desanimar nem desmerecer o trabalho do @ricardotominaga 

Ontem saiu uma nova versão da aplicação, onde a lib agora está colocando na chave obtenos algum parâmetro do aparelho (que não conseguir identificar), uma nova URL (/v3).
Então futuramente essa versão vai parar de funcionar.
Alguma logica mudou, acredito que a propriedade que a lib pega do aparelho é também enviada no XML, talvez o modelo do aparelho.

**Comment by vjoao** [comment]
Já atualizamos nossa solução.

**Comment by ricardotominaga** [comment]
A nova versão tá montando a hash aparentemente assim: 

`hmac(plate+'#8.1.0#Mw6HqdLgQsX41xAGZgsF', plate, sha1).hexdigest()`

Ainda não descobri o que é esse 8.1.0

Alguém poderia mandar um xml novo de exemplo?

**Comment by fabioravila** [comment]
@ricardotominaga 
Por chute, acredito que seja a versão d o android.
O android que está testando é o Oreo? Se for é isso mesmo.

**Comment by fabiovianna89** [comment]
Podem enviar o link do discord por favor? Quero tentar ajudar de alguma forma tbm

**Comment by ricardotominaga** [comment]
Nova URL:

`https://189.9.194.154/sinesp-cidadao/mobile/consultar-placa/v3`

Exemplo do XML:

```
<v:Envelope xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:d="http://www.w3.org/2001/XMLSchema" xmlns:c="http://schemas.xmlsoap.org/soap/encoding/" xmlns:v="http://schemas.xmlsoap.org/soap/envelope/">
	<v:Header>
		<b>Google Android SDK built for x86</b>
		<c>ANDROID</c>
		<d>8.1.0</d>
		<e>4.3.2</e>
		<f>10.0.2.15</f>
		<g>708580ba5d15931bb6674c1e9498eb870d367316</g>
		<h>0.0</h>
		<i>0.0</i>
		<k />
		<l>2018-01-31 20:10:05</l>
		<m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m>
	</v:Header>
	<v:Body>
		<n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/">
			<a>FFF1242</a>
		</n0:getStatus>
	</v:Body>
</v:Envelope>
```

**Comment by fabioravila** [comment]
Então parece que agora a lib está pegando a versão atual do android, adicionando no hash, e passando a mesma versão no XML na tag <d>, que antes enviava o platformBuildVersionName no app.

**Comment by NewZeek** [comment]
Para nova URL, a chave deve ser montada incluindo a mesma versão do Android especificada na tag `<d></d>` do XML, como por exemplo: 
`  android_version = '7.0'`
`secret_key = '#' + android_version + '#Mw6HqdLgQsX41xAGZgsF'`

XML:
`             ...
		<d> android_version </d>
		...`
Ao enviar a requisição, o webservice gera novamente o hash utilizando como chave a versao do android enviada na tag `<d>` mais a chave "Mw6HqdLgQsX41xAGZgsF" e compara com o hash especificado na tag `<g></g>` do XML.

URL: https://189.9.194.154/sinesp-cidadao/mobile/consultar-placa/v3

No momento ambas as urls estão funcionando.

**Comment by fabiovianna89** [comment]
Estou tentando gerar essa chave pelo c#... mas por algum motivo ele está fazendo isso errado.

estou usando esse código:


private string secret = "#8.1.0#Mw6HqdLgQsX41xAGZgsF";
private string placa = "";


 string key = secret;
                System.Text.ASCIIEncoding encoding = new System.Text.ASCIIEncoding();
                byte[] keyByte = encoding.GetBytes(key);
                HMACSHA1 hmacsha1 = new HMACSHA1(keyByte);
                byte[] messageBytes = encoding.GetBytes(placa);

                byte[] hashmessage = hmacsha1.ComputeHash(messageBytes);

                string hmac2 = ByteToString(hashmessage);

private string ByteToString(byte[] buff)
        {
            string sbinary = "";

            for (int i = 0; i < buff.Length; i++)
            {
                sbinary += buff[i].ToString("X2"); // hex format
            }
            return (sbinary);
        }

**Comment by fabiovianna89** [comment]
problema resolvido...

**Comment by victor-torres** [comment]
@ricardotominaga parabéns pela solução. Gostaria de fazer um pull request para o repositório acrescentando teu usuário à lista de contribuidores?

**Comment by fabiovianna89** [comment]
Apenas para ajudar quem está chegando a chave secret precisa da Placa também.

ficando:
private string secret = placa + "#8.1.0#Mw6HqdLgQsX41xAGZgsF";

**Comment by lucas-boldt** [comment]
@fabiovianna89  você pensa em disponibilizar o seu código C#?

**Comment by fabiovianna89** [comment]
Pose deixar... Subo o código hoje no git e deixo o link aqui.

**Comment by fabiovianna89** [comment]
Segue o link com o projeto feito em C#...

Caso tenham algum grupo no discord, gostaria de participar para poder ajudar la tbm.

Abraços,

https://github.com/fabiovianna89/SINESP_Consulta

**Comment by lucas-boldt** [comment]
Obrigado!
Há sim um grupo no discord. Pedi para um dos adms enviar um convite aqui.

**Comment by pedrovilela** [comment]
Olá a todos, bom trabalho em conseguirem a chave nova, ja fiz o ajustes para o codigo python, só falta o @victor-torres, aceitar o pull-request.

**Comment by lagden** [comment]
Alguém fez uma mapa das mensagens de erro?
Estou fazendo um módulo para Node.js

**Comment by lagden** [comment]
Tenho esses por enquanto...

```js
{
  "codigoRetorno": "0",
  "mensagemRetorno": "Sem erros.",
  "codigoRetorno": "1",
  "mensagemRetorno": "Erro no processamento da consulta."
  "codigoRetorno": "3",
  "mensagemRetorno": "Veículo não encontrado."
}
```

**Comment by lagden** [comment]
esta no ar...

https://github.com/lagden/placa

e a lib no npm: https://www.npmjs.com/package/@tadashi/placa

Obrigado @victor-torres

**Comment by luciocorrea** [comment]
@lagden Pelo menos agradece ao @ricardotominaga também, né?

**Comment by lagden** [comment]
Obrigado @ricardotominaga...

:godmode:

**Comment by victor-torres** [comment]
Obrigado a todos os envolvidos. Acabei de fechar o pull request #31 e lancei a versão 1.10 da biblioteca do sinesp-client no PyPI. Tomei a liberdade de adicionar o Ricargo Tominaga (o primeiro a compartilhar o novo hash aqui) e o Pedro Vilela (autor do comentário) à lista de contribuidores, mas reconheço a importância de todos envolvidos no processo. Até a próxima! rsrs

**Comment by ritielmi** [comment]
Olá @victor-torres , primeiramente obrigado por fornecer e ensinar seu conhecimento sobre essa ferramenta. Tenho acompanhado o seu desenvolvimento do sinsp cidadão há um certo tempo.
Atualizei meu app em PHP semana passada com a ultima chave que você postou Mw6HqdLgQsX41xAGZgsF MAS INFELIZMENTE PAROU NOVAMENTE. codigoRetorno = 7
mensagemRetorno = Versão desatualizada. Favor atualizar aplicativo.

**Comment by victor-torres** [comment]
Olá, @ritielmi. 

O que você gostaria de saber sobre a mudança de API? Todas as descobertas estão nesta thread e as mudanças podem ser vistas na íntegra nos commits deste repositório. 

Ah, se for possível, evite duplicar mensagens. O mesmo texto foi publicado no pull request #31

**Comment by ritielmi** [comment]
Certo, obrigado pela rápida atenção. A princípio vi que a chave e a url foi alterada. Gostaria de saber se tenho que fazer alguma alteração no XML também. Achei estranho porque após a alteração da url e da chave voltou a funcionar mas por poucos dias...

**Comment by victor-torres** [comment]
@ritielmi dê uma olhada nos dois últimos pull requests, #31 e #32. Lá você vai ver o que mudou em relação à chave, parâmetros e XML. 

A /v2 parece que parou de funcionar, mas já estamos usando a /v3.

**Comment by jpdesignerrio** [comment]
Li tudo que está aqui, mas ainda não funcionou em PHP...

**Comment by luciocorrea** [comment]
@jpdesignerrio https://github.com/chapeupreto/sinesp

**Comment by jpdesignerrio** [comment]
@luciocorrea está retornando ```
<codigoRetorno>7</codigoRetorno>
<mensagemRetorno>Versão desatualizada. Favor atualizar aplicativo.</mensagemRetorno>
``` tanto em PHP como testando no REST Client

**Comment by jpdesignerrio** [comment]
@luciocorrea Encontrei o problema, a tag `<l>` estava vazia, por algum motivo a função `strftime('%Y-%m-%d %T')` não está retornando a data e hora no wampserver. Obrigado pelo link.

**Comment by chapeupreto** [comment]
@jpdesignerrio É porque a opção `%T` realmente não funciona em sistemas Windows.  Alterei agora para usar a forma antiga `%H:%M:%S`

**Comment by ritielmi** [comment]
Bom dia Senhores. Acredito que o sinesp fez uma nova atualização. Hoje pela manhã fui testar e apareceu a famosa mensagem "Versão desatualizada. Favor atualizar aplicativo". Observação: Até ontem (01/07/2019) estava funcionando...

**Comment by edersongoulart** [comment]
Bom dia! 

Realmente @ritielmi . Alguém tem alguma ideia de como resolver?

**Comment by Mario-HL-Duarte** [comment]
Mudaram a URL, o XML, o Header da requisição e **A CHAVE**

**Comment by edersongoulart** [comment]
Boa tarde meu querido @Mario-HL-Duarte  .

Conseguiria nos ajudar?

**Comment by Mario-HL-Duarte** [comment]
Calma.
Essas coisas levam tempo.
As vezes, muuuuito tempo!

**Comment by GralakCobra** [comment]
Alguém tem alguma novidade sobre o assunto para nos ajudar por favor ?

**Comment by sconetto** [comment]
@ritielmi tem alguma forma que eu possa ajudar?
Estou usando o cliente e apareceu a mensagem de versão desatualizada

**Comment by ritielmi** [comment]
@sconetto  o pessoal está quase conseguindo...

**Comment by sconetto** [comment]
@ritielmi sim eu estou acompanhando, parece já conseguiram a chave

**Comment by GralakCobra** [comment]
Se alguém conseguiu poste a solução para gente aqui fazendo um grande imenso favor mesmo kkkk

**Comment by sconetto** [comment]
@GralakCobra https://github.com/chapeupreto/sinesp/issues/37#issuecomment-508722919
mas pelo que estou vendo das discussões abaixo parece que o token tem um limite de consulta:
https://github.com/chapeupreto/sinesp/issues/37#issuecomment-508797938

**Comment by carloscte** [comment]
@sconetto Na verdade, o que acontece é que o aplicativo gera um TOKEN do Firebase. Esse TOKEN tem, acredito, uma data de expiração. Por isso que com um determinado TOKEN não é possível consultar indefinidamente.

A grande questão é: É possível uma aplicação gerar um token válido assim como o aplicativo do SINESP?

**Comment by WaldiirNeto** [comment]
Como o Carlos Falou, impossivel. o token precisa ser autenticado no próprio servidor firebase!!!
