### ISSUE TITLE
Google Cloud: ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by ladyclementine** [victor-torres/sinesp-client#33]
Mesmo com uma máquina virtual montada a partir do Google Cloud, com zona southamerica-east1-b, ou seja, no Brasil, SP, não consigo fazer a requisição.  Alguém já teve algum problema assim ou parecido?

**Comment by fabioravila** [comment]
Normalmente esse erro é relacionado à bloqueio de IP´s.
Pode ser que o SINESP tenha bloqueado acesso aos ips do Google Cloud, Azure e etc.

**Comment by victor-torres** [comment]
Como conversado por e-mail, a solução seria usar um servidor proxy. Mas eu não tenho nenhum para indicar. Alguém que usa a solução desta forma poderia compartilhar uma lista de serviços ou recomendações?

**Comment by rickduarte** [comment]
Nesse site tem uma lista dos proxies gratuitos:
[http://www.freeproxylists.net/?c=BR&pt=&pr=&a%5B%5D=0&a%5B%5D=1&a%5B%5D=2&u=70](http://www.freeproxylists.net)

**Comment by chapeupreto** [comment]
Proxies pagos: `https://kingproxies.com/`

**Comment by victor-torres** [comment]
Estou fechando a issue, visto que não se trata de um problema no projeto em si e já temos algumas sugestões de como contornar o problema. Mas sintam-se à vontade para continuar a discussão aqui nesta thread.
