### ISSUE TITLE
Result = None

### ISSUE THREAD

**Issue by jegue** [victor-torres/sinesp-client#34]
todas as consultas estão retornando None! 
ele conecta mas nao popula.

[('city', None), ('model_year', None), ('plate', None), ('color', None), ('status_code', None), ('brand', None), ('return_code', '1'), ('date', None), ('state', None), ('chassis', None), ('year', None), ('return_message', u'N\xe3o foi poss\xedvel estabelecer comunica\xe7\xe3o entre Sinesp Cidad\xe3o e RENAVAM.'), ('model', None), ('status_message', None)]

**Comment by jegue** [comment]
voltou

**Comment by LuizFernandoCabral** [comment]
Isso geralmente se deve pelo sistema do governo estar fora do ar (bem comum de acontecer)

**Comment by victor-torres** [comment]
Correto o que o Luiz falou. Somente observe que nem todos os campos são indefinidos. Há uma mensagem de retorno descrevendo o problema vinda direto do SINESP, alegando falha de comunicação com o RENAVAM.
