### ISSUE TITLE
Versão desatualizada

### ISSUE THREAD

**Issue by arapinha** [victor-torres/sinesp-client#36]
Estou recebendo a mensagem: Código: 7 - Versão desatualizada. Favor atualizar aplicativo.

**Comment by EmersonHenriique** [comment]
Para melhor comunicação https://discord.gg/3shuzyT

**Comment by victor-torres** [comment]
Atualizem a versão da bilioteca. O @pedrovilela adicionou suporte à API v4 do SINESP. Trocaram apenas o endpoint e a palavra-passe.
