### ISSUE TITLE
Problema na conexão após executar o python

### ISSUE THREAD

**Issue by MauMau2** [victor-torres/sinesp-client#38]
/usr/local/lib/python2.7/dist-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Por favor tem alguma forma de contornar isso?
Desde já agradeço

**Comment by rodrigodellajustina** [comment]
Solucionei da seguinte forma:
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

**Comment by victor-torres** [comment]
Isso é um Warning, um Alerta, que diferentemente de um erro não impede o funcionamento do programa.

Nesse caso, o alerta indica que o certificado SSL/TLS utilizado pelo SINESP não é válido.

**Comment by MauMau2** [comment]
Perfeita a dica do Rodrigo, já alterei o código e funcionou, obrigado!
