### ISSUE TITLE
Dúvida sobre o .py

### ISSUE THREAD

**Issue by doidloko** [victor-torres/sinesp-client#4]
Existe alguma outra forma de utilizar este seu código sem precisar entrar no ssh?
pip install sinesp-client
Minha hospedagem roda os arquivos .py porém não tenho acesso ao ssh por ela ser compartilhada.
Há alguma outra maneira de utilizar este mesmo código sem a linha de código install?

Obrigado

**Comment by victor-torres** [comment]
Você pode conversar com o suporte do seu provedor de hospedagem, mas o ideal mesmo seria migrar para um outro tipo de hospedagem que permita o acesso via SSH e a instalação de bibliotecas Python. Uma boa solução seria um serviço de VPS como a Digital Ocean ou Linode. Se preferir opções nacionais existe a UOL Host, por exemplo e diversas outras.
