### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by enigma-watcher** [victor-torres/sinesp-client#41]
![screenshot_20180813-101320_sinesp cidadao](https://user-images.githubusercontent.com/42346260/44035123-1a1d963c-9ee5-11e8-9565-cb7ae05bd0b3.jpg)

**Comment by lagden** [comment]
Mas não estamos acessando o banco de dados deles.
Estamos acessando a API aberta deles, logo eles que estão divulgando.

Aqui, nada é comercializado e nem armazenado...

E também estes dados deveriam ser de domínio público, já que somos nós que pagamos por ele (impostos).

**Comment by victor-torres** [comment]
Concordo com o @lagden.

> O crime de invasão de dispositivo informático consiste no fato de o agente “invadir dispositivo informático alheio, conectado ou não à rede de computadores, mediante violação indevida de mecanismo de segurança e com o fim de obter, adulterar ou destruir dados ou informações sem autorização expressa ou tácita do titular do dispositivo ou instalar vulnerabilidades para obter vantagem ilícita” (CP, art. 154-A, caput).

Não estamos acessando ao banco de dados diretamente. O que a biblioteca faz é consumir uma API de uma informação que já é pública hoje. Qualquer um pode obtê-la através do aplicativo ou site do SINESP. Aliás, já passou da hora de obtermos uma API oficial que ofereceça um suporte melhor para a consulta automatizada dessas informações.

Isso possibilitaria inúmeras inovações tecnológicas por iniciativa dos cidadãos brasileiros, que contribuiriam bastante para o aumento da segurança pública e permitiria uma melhor cooperação entre o setor público e a iniciativa privada.

Por exemplo, já ouvi falar de diversos estacionamentos que utilizam as informações abertas do SINESP para verificar se veículos irregulares ou com alerta de furto/roubo estão em seus estabelecimentos. Isso contribui para a segurança de todos e pode agilizar o serviço da polícia.

Desconheço a utilização de tais sistemas para o cometimento de fraudes. Até porque se alguém deseja, por exemplo, adulterar um veículo copiando dados de um veículo de características semelhantes, assim poderá fazê-lo de outras formas, inclusive utilizando o próprio site ou aplicativo do SINESP. Mas ainda assim, seria improvável, pois a plataforma apenas fornece alguns dados básicos, ofuscando dados importantes como número completo de chassi etc.

O trabalho feito aqui é totalmente voluntário e não há qualquer tipo de invasão de dispositivos terceiros ou subtração de dados. 

Por último, considero no mínimo estranho que uma conta criada há apenas 6 horas e sem contribuições e qualquer outra atividade no Github tenha vindo aqui apenas publicar este "alerta".

Se houver qualquer interesse de diálogo, reforço que o meu e-mail está público em meu perfil no Github. Por favor, peço que entrem em contato, caso exista interesse em um diálogo, comunicação oficial ou parceria.

Estou fechando a issue, mas a discussão permanece aberta.
