### ISSUE TITLE
Atualizar a API para consultar placas no padrão Mercosul

### ISSUE THREAD

**Issue by joaokhaled** [victor-torres/sinesp-client#42]

**Comment by victor-torres** [comment]
Você sabe dizer se o aplicativo já funciona com placas no novo padrão? Eu acabei de testar e aparentemente não funciona ainda. 

Vou fechar a issue por enquanto. Eu acredito que quando o suporte for adicionado ao aplicativo, das duas, uma:

- o suporte vai ser automaticamente adicionado a esta biblioteca, sem precisarmos fazer nada
- a biblioteca vai quebrar devido a uma atualização na autenticação da api

**Comment by chapeupreto** [comment]
A versão `v4.6-1` do aplicativo já possibilita a consulta por placas no padrão Mercosul.

A versão da biblioteca escrita em [PHP](https://github.com/chapeupreto/sinesp) já foi adaptada para aceitar esse novo formato e até agora está funcionando normalmente.

**Comment by victor-torres** [comment]
Perfeito então! Obrigado pelos detalhes, @chapeupreto.

**Comment by victor-torres** [comment]
@chapeupreto, eu dei uma olhada no repositório, mas além da validação e limpeza feita do lado da bilioteca, não consegui identificar alguma modificação na API do SINESP. 

Como esta biblioteca Python não faz validação dos dados de entrada (a placa, no caso), acredito que já deva estar funcionando. 

Então se você tem uma placa `ABC-123F`, se você chamar a biblioteca com `sc.search('ABC123F')`, em teoria, deveria funcionar.

Se não estiver funcionando pra vocês, peço que comentem algum exemplo de placa que deveria estar funcionando, mas não está, por aqui ou por e-mail.

**Comment by chapeupreto** [comment]
Do lado da API do SINESP realmente não houve nenhuma alteração. No caso da biblioteca, o único ajuste que foi necessário foi somente nessa parte da validação da placa mesmo. Eu também acredito que essa lib aqui já esteja funcionando sem problemas.

**Comment by victor-torres** [comment]
Obrigado pela contribuição mais uma vez :)
