### ISSUE TITLE
Estou recebendo o seguinte erro ao fazer uma consulta:

### ISSUE THREAD

**Issue by joaokhaled** [victor-torres/sinesp-client#43]
`Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner                        self.run()                                               File "/data/data/com.termux/files/usr/lib/python3.7/threading.py", line 865, in run                                     self._target(*self._args, **self._kwargs)                File "main.py", line 38, in handle                           d = sc.search(a)                                         File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sinesp_client/__init__.py", line 176, in search       response = self._request(plate).content                  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sinesp_client/__init__.py", line 105, in _request     cookies = self._captcha_cookie()                         File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/sinesp_client/__init__.py", line 95, in _captcha_cookie                                                          cookies = requests.get('https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/captchaMobile.png', proxies=self._proxies, verify=False).cookies                                    File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get                     return request('get', url, params=params, **kwargs)      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request                 return session.request(method=method, url=url, **kwargs)                                                            File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request           resp = self.send(prep, **send_kwargs)                    File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send              r = adapter.send(request, **kwargs)                      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send              raise ConnectionError(err, request=request)            requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x00[\x00\x00\x00\x00\x00\x00'))`

**Comment by victor-torres** [comment]
Parece ter sido uma falha de conexão temporária. Está usando algum proxy?

**Comment by joaokhaled** [comment]
não, qual o limite de consultas diárias?


Em seg, 28 de jan de 2019 09:33, Victor Torres <notifications@github.com>
escreveu:

**Comment by lagden** [comment]
@joaokhaled 
Apenas uma observação: A API só funciona em território nacional, se sua hospedagem for fora do país é necessário o uso de proxy!

**Comment by victor-torres** [comment]
@joaokhaled, o limite de requisições é desconhecido pela comunidade.

Acredito que um limite seguro seja realizar até 20 requests por minuto.
