### ISSUE TITLE
Flask + SinespClient

### ISSUE THREAD

**Issue by 01viniciusmelo** [victor-torres/sinesp-client#44]
Estou criando um serviço REST com Flask e estou obtendo o seguinte erro:

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Meu arquivo Python está assim:

import json
import sys

from sinesp_client import SinespClient
from flask import Flask, request
from flask_restful import Resource, Api
from json import dumps

app = Flask(__name__)
api = Api(app)

class Placa(Resource):
    def get(self, placa):
        sc = SinespClient()
        result = sc.search('ABC1234')
        json_result = json.dumps(result)
        return {'placa': json_result}

api.add_resource(Placa, '/<placa>')

if __name__ == '__main__':
    app.run(debug=True)

Usando proxy 200.170.220.218:8080 (mesmo proxy usado no serviço PHP do chapeupreto que uso em um website meu) estou tendo o seguinte erro:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='sinespcidadao.sinesp.gov.br', port=443): Max retries exceeded with url: /sinesp-cidadao/captchaMobile.png (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f96ef196710>: Failed to establish a new connection: [Errno 110] Connection timed out',)))

**Comment by victor-torres** [comment]
Eu testei e o serviço está OK pra mim. Deve ser algum problema com a sua conexão. 

- não tem como garantir se o problema de conexão é causado pelo sinesp ou pela rede que você está conectado
- veja que não é possível nem se conectar ao seu servidor proxy, o que pode ser mais um indicativo de problema ou limitação da sua rede

O script PHP que você roda não é na mesma máquina/rede, né? Deve ser por isso que nele funciona...

**Comment by 01viniciusmelo** [comment]
Tudo funcionando no Flask. Obrigado pelas orientações.
