### ISSUE TITLE
Versão desatualizada

### ISSUE THREAD

**Issue by 100n0m3** [victor-torres/sinesp-client#45]
Update 02-07-2019 Parou de funcionar

**Comment by theclanks** [comment]
https://github.com/Sorackb/sinesp-api/issues/79

**Comment by Pedroasilva** [comment]
https://github.com/chapeupreto/sinesp/issues/37

**Comment by carloscte** [comment]
Alguma novidade?

**Comment by sconetto** [comment]
@victor-torres parece que conseguiram a chave nova no https://github.com/chapeupreto/sinesp/issues/37, será que é só mudar numa branch aqui no sinesp_client?

**Comment by victor-torres** [comment]
Estou disponibilizando uma prova de conceito com uma nova de automatizar as consultas ao SINESP. É uma forma não invasiva e não depende de engenharia reversa do aplicativo. https://github.com/victor-torres/sinesp-bot

**Comment by joaokhaled** [comment]
ainda achava o sinespcli mais efetivo, espero atualizações, implemento um bot telegram.

**Comment by lagden** [comment]
@victor-torres será que uns twitter pro @jairbolsonaro não ajudaria a liberar a API pra consulta?

**Comment by SouzaRDG** [comment]
Ainda sairá novas atualizações? Das soluções que eu encontrei essa era sem dúvida a melhor...

**Comment by victor-torres** [comment]
Reabrindo a issue pra ficar visível aos novos usuários, mas o status continua o mesmo. Basicamente um **won't fix**.
