### ISSUE TITLE
Erro 7 - Versão aplicativo desatualizada

### ISSUE THREAD

**Issue by mclgms** [victor-torres/sinesp-client#46]
Estou tentando utilizar a biblioteca e estou recebendo este erro:

 InsecureRequestWarning)
{"city": null, "model_year": null, "plate": null, "color": null, "status_code": null, "brand": null, "return_code": "7", "date": null, "state": null, "chassis": null, "year": null, "return_message": "Vers\u00e3o desatualizada. Favor atualizar aplicativo.", "model": null, "status_message": null}

Tenho que setar mais algum parâmetro?

**Comment by victor-torres** [comment]
https://github.com/victor-torres/sinesp-client/issues/45#issuecomment-508892339
