### ISSUE TITLE
Versão desatualizada. Favor atualizar aplicativo

### ISSUE THREAD

**Issue by sadbut-1** [victor-torres/sinesp-client#47]
Fui realizar uma consulta e o resultado foi esse. Essa API ainda esta funcionando?

{
    "dados": {
        "return_code": "7",
        "return_message": "Versão desatualizada. Favor atualizar aplicativo.",
        "status_code": null,
        "status_message": null,
        "chassis": null,
        "model": null,
        "brand": null,
        "color": null,
        "year": null,
        "model_year": null,
        "plate": null,
        "date": null,
        "city": null,
        "state": null
    }
}

**Comment by victor-torres** [comment]
https://github.com/victor-torres/sinesp-client/issues/45#issuecomment-508892339
