### ISSUE TITLE
ImportError: cannot import name 'DependencyWarning'

### ISSUE THREAD

**Issue by mdamaceno** [victor-torres/sinesp-client#5]
Estou usando o script dentro de um projeto PHP, mas mesmo no console do Python, dá o seguinte erro:

```
Traceback (most recent call last):
  File "/home/mdamaceno/Desenvolvimento/php/laravel/plate.py", line 4, in <module>
    from sinesp_client import SinespClient
  File "/usr/lib/python3.5/site-packages/sinesp_client/__init__.py", line 8, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
```

Acho que há um problema na importação da dependência. Confirma?

**Comment by wschoenell** [comment]
O problema é na sua instalação do Python.

**Comment by mdamaceno** [comment]
Bom, eu uso o Manjaro, distribuição baseada no Arch Linux. Quando eu digito `python` no terminal, ele abre o console e me informa a versão:

```
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Você quer dizer que o Python que já vem pré instalado está com problemas? Alguma sugestão?

**Comment by wschoenell** [comment]
https://bugs.archlinux.org/task/49163
