### ISSUE TITLE
Problema de Captcha ao realizar várias requisições

### ISSUE THREAD

**Issue by alphabraga** [victor-torres/sinesp-client#6]
Quando eu tento realizar várias requisições o erro do Captcha aparece...

Output:

/sinesp.py PSL8397
{"city": "SAO LUIS", "model_year": "2016", "plate": "PSL8397", "color": "CINZA", "status_code": "0", "brand": "BMW/320I ACTIVE FLEX", "return_code": "0", "date": "10/06/2016 \u00e0s 12:36:11", "state": "MA", "chassis": "************32003", "year": "2015", "return_message": "Sem erros.", "model": "BMW/320I ACTIVE FLEX", "status_message": "Sem restri\u00e7\u00e3o"}
 ./sinesp.py PSL8397
{"city": "SAO LUIS", "model_year": "2016", "plate": "PSL8397", "color": "CINZA", "status_code": "0", "brand": "BMW/320I ACTIVE FLEX", "return_code": "0", "date": "10/06/2016 \u00e0s 12:36:12", "state": "MA", "chassis": "************32003", "year": "2015", "return_message": "Sem erros.", "model": "BMW/320I ACTIVE FLEX", "status_message": "Sem restri\u00e7\u00e3o"}
 ./sinesp.py PSL8397
{"city": null, "model_year": null, "plate": null, "color": null, "status_code": null, "brand": null, "return_code": "5", "date": null, "state": null, "chassis": null, "year": null, "return_message": "Captcha inv\u00e1lido.", "model": null, "status_message": null}

**Comment by victor-torres** [comment]
Percebi que as consultas foram feitas em um intervalo bem pequeno de tempo, provavelmente menos do que um segundo.

Parece ser uma limitação justa implementada pelo SINESP para evitar abusos na utilização da API.

Você pode aumentar o tempo entre as consultas ou o problema acontece mesmo com intervalos maiores?

**Comment by alphabraga** [comment]
Sim. Realizei a mesma consulta varias vezes... num intervals pequeno. Queria testar a solucão.

A proposito , parabéns!

Que pena que nao exista uma API oficial, imagine quanto o estado nao iria economizar compartilhando essas informações....

**Comment by victor-torres** [comment]
OK. Fechando a issue então.

**Comment by victor-torres** [comment]
Obrigado!
