### ISSUE TITLE
Mudança de URL

### ISSUE THREAD

**Issue by manoelt** [victor-torres/sinesp-client#7]
Victor,

Houve uma mudança de URL, a atual não está respondendo. Apenas comentando por aqui, mas pretendo dar uma olhada na nova apk.

Valeu.

**Comment by manoelt** [comment]
Bobeira minha, bloqueram meu ip. :)

**Comment by mdamaceno** [comment]
Pode dizer qual IP vc ta usando? Estou tentando aqui e só dá timeout.

**Comment by victor-torres** [comment]
Tente utilizar um proxy. Existem vários gratuitos na internet. Tem exemplo
de utilização na documentação do projeto.

Evite abusar nos requests também.
Em qua, 24 de ago de 2016 às 15:39, Marco Damaceno <notifications@github.com>
escreveu:

**Comment by manoelt** [comment]
Passei a utilizar proxy pública do Brasil também. Estava utilizando IP do US e sem fazer abusos fui banido.
