### ISSUE TITLE
Licença

### ISSUE THREAD

**Issue by fpg1503** [victor-torres/sinesp-client#8]
Qual a licença do seu código?

**Comment by victor-torres** [comment]
Ainda não parei pra definir uma licença de código, mas espero que seja feita uma contribuição/doação caso o projeto em que ele seja utilizado possua algum valor comercial. Os valores vão depender da dimensão do negócio e de quanto a organização/projeto pode e deseja doar.

Mas se fosse para escolher uma hoje, acho que escolheria MIT.

**Comment by fpg1503** [comment]
Estou fazendo um wrapper em Swift do Sinesp e usei seu código como referência mas fiquei com dúvida na hora de qual licença colocar, estava pensando em colocar MIT, os créditos para seu projeto estão no meu `README.md`, o que acha?

**Comment by victor-torres** [comment]
Tudo bem @fpg1503
