### ISSUE TITLE
Não consigo conectar usando proxy

### ISSUE THREAD

**Issue by alduxx** [victor-torres/sinesp-client#9]
Oi Vitor,

Não estou conseguindo fazer funcionar utilizando proxy socks5.
Estou instanciando:

`sc = SinespClient( proxy_address='200.240.227.181', proxy_port=30828)`

Mas recebo o erro:
`[Fri Aug 26 15:18:44.291049 2016] [wsgi:error] [pid 22798:tid 2948696976] [remote 127.0.0.1:0] requests.exceptions.ProxyError: HTTPConnectionPool(host='200.240.227.181', port=30828): Max retries exceeded with url: http://sinespcidadao.sinesp.gov.br/sinesp-cidadao/ConsultaPlacaNovo02102014 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(104, 'Connection reset by peer')))`

Eu verifiquei o proxy e ele está funcionando...

Quaquer ajuda é muito bem vinda!

**Comment by victor-torres** [comment]
Use um outro servidor proxy. Esse não irá funcionar com o SINESP.

**Comment by thiagotalma** [comment]
@victor-torres, alguma dica de onde encontrar uma lista boa de proxys válidos?
Acho milhares de listas procurando pelo Google, mas nenhuma delas tem resultados confiáveis.
Obrigado!

**Comment by victor-torres** [comment]
@thiagotalma gratuitos são difíceis de achar. Tem que ir procurando naquelas listas imensas e torcer pra que um dê certo. Talvez você tenha um pouco mais de sorte utilizando um proxy pago ou configurando um particular em um servidor remoto. Infelizmente não possui nenhuma indicação.
